version: "3"
services:
        mysql:
                build: ./
                volumes:
                        - ./db:/docker-entrypoint-initdb.d
                image: original_mysql_world
                environment:
                        - MYSQL_ROOT_PASSWORD=testpassword
